name: Astro Inspection

on:
  pull_request:
    paths:
      - '**/*.astro'
      - 'astro.config.*'
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build